name: Deploy to ECR
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build Image
    runs-on: windows-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - run: docker build -t c360 .
    - name: Push to ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: AKIA2TRO5ZCMAXIIQNJB
        secret-access-key: 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
        region: ap-southeast-1
        local-image: c360
        image: c360, c360:latest